<?xml version="1.0"?>
<robot name="plugins" xmlns:xacro="http://ros.org/wiki/xacro">

    <!-- Constants -->
    <xacro:include filename="$(find description)/urdf/constants.xacro"/>
    
    <!-- Differential Drive Controller -->
    <!-- <gazebo>
        <plugin name="differential_drive_controller" filename="libgazebo_ros_diff_drive.so">

            <alwaysOn>true</alwaysOn>
            <legacyMode>false</legacyMode>
            <rosDebugLevel>na</rosDebugLevel> -->

            <!-- Plugin update rate (Hz) -->
            <!-- <updateRate>30</updateRate> -->
            
            <!-- Name of joints connecting to wheels -->
            <!-- <leftJoint>front_left_wheel_joint</leftJoint>
            <rightJoint>front_right_wheel_joint</rightJoint> -->

            <!-- Wheel properties -->
            <!-- <wheelSeparation>${wheel_separation}</wheelSeparation>
            <wheelDiameter>${2.0 * wheel_radius}</wheelDiameter>
            <wheelAcceleration>0</wheelAcceleration>
            <wheelTorque>5</wheelTorque>
            <torque>5</torque> -->

            <!-- Topic to receive geometry_msgs/Twist message commands -->
            <!-- <commandTopic>cmd_vel</commandTopic> -->

            <!-- Odometry (nav_msgs/Odometry) settings -->
            <!-- <odometrySource>world</odometrySource>
            <odometryTopic>odom</odometryTopic>
            <odometryFrame>odom</odometryFrame> -->

            <!-- Robot frame to calculate odometry from -->
            <!-- <robotBaseFrame>base_link</robotBaseFrame> -->

            <!-- Publish TF frames -->
            <!-- <publishTf>true</publishTf>
            <publishOdomTF>true</publishOdomTF>

            <publishWheelTF>false</publishWheelTF>
            <publishWheelJointState>true</publishWheelJointState>

        </plugin>
    </gazebo> -->

    <!-- <gazebo>
        <plugin name="skid_steer_drive_controller" filename="libgazebo_ros_skid_steer_drive.so">
            <updateRate>30.0</updateRate>
            <robotNamespace>/</robotNamespace>
            <leftFrontJoint>front_left_wheel_joint</leftFrontJoint>
            <rightFrontJoint>front_right_wheel_joint</rightFrontJoint>
            <leftRearJoint>back_left_wheel_joint</leftRearJoint>
            <rightRearJoint>back_right_wheel_joint</rightRearJoint>
            <wheelSeparation>${wheel_separation}</wheelSeparation>
            <wheelDiameter>${2.0 * wheel_radius}</wheelDiameter>
            <robotBaseFrame>base_link</robotBaseFrame>
            <torque>20</torque>
            <topicName>cmd_vel</topicName>
            <broadcastTF>false</broadcastTF>
        </plugin>
    </gazebo> -->

    <gazebo>
        <plugin name="object_controller" filename="libgazebo_ros_planar_move.so">
            <commandTopic>cmd_vel</commandTopic>
            <odometryTopic>odom</odometryTopic>
            <odometryFrame>odom</odometryFrame>
            <odometryRate>20.0</odometryRate>
            <robotBaseFrame>base_link</robotBaseFrame>
        </plugin>
    </gazebo>

    <!-- lets all the transmission tags be read -->
    <!-- <gazebo>
        <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so"/>
    </gazebo> -->

</robot>
