<?xml version="1.0"?>
<robot name="plugins" xmlns:xacro="http://ros.org/wiki/xacro">

    <!-- Constants -->
    <xacro:include filename="$(find description)/urdf/constants.xacro"/>

    <!-- Differential Drive Controller -->
    <gazebo>
        <plugin name="differential_drive_controller" filename="libgazebo_ros_diff_drive.so">

            <alwaysOn>true</alwaysOn>
            <legacyMode>false</legacyMode>
            <rosDebugLevel>na</rosDebugLevel>

            <!-- Plugin update rate (Hz) -->
            <updateRate>30</updateRate>
            
            <!-- Name of joints connecting to wheels -->
            <leftJoint>front_left_wheel_joint</leftJoint>
            <rightJoint>front_right_wheel_joint</rightJoint>

            <!-- Wheel properties -->
            <wheelSeparation>${wheel_separation}</wheelSeparation>
            <wheelDiameter>${2.0 * wheel_radius}</wheelDiameter>
            <wheelAcceleration>0</wheelAcceleration>
            <wheelTorque>5</wheelTorque>
            <torque>5</torque>

            <!-- Topic to receive geometry_msgs/Twist message commands -->
            <commandTopic>cmd_vel</commandTopic>

            <!-- Odometry (nav_msgs/Odometry) settings -->
            <odometrySource>world</odometrySource>
            <odometryTopic>odom</odometryTopic>
            <odometryFrame>odom</odometryFrame>

            <!-- Robot frame to calculate odometry from -->
            <robotBaseFrame>base_link</robotBaseFrame>

            <!-- Publish TF frames -->
            <publishTf>true</publishTf>
            <publishOdomTF>true</publishOdomTF>

            <publishWheelTF>false</publishWheelTF>
            <publishWheelJointState>true</publishWheelJointState>

            <!-- TODO: enforce velocity/acceleration limits -->

        </plugin>
    </gazebo>

    <!-- ROS Control: Reads transmission tags -->
    <gazebo>
        <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so"/>
    </gazebo>

    <!-- IR Sensor: Range Sensor -->
    <xacro:property name="range_sensor_fov" value="${5*pi/180}"/>
    <xacro:property name="range_sensor_update_rate" value="50"/>
    <xacro:property name="range_sensor_max_range" value="0.8"/>

    <gazebo reference="base_ir_link">        
        <sensor type="ray" name="RangeSensor">
            <pose>0 0 0 0 0 0</pose>
            <visualize>false</visualize>
            <update_rate>${range_sensor_update_rate}</update_rate>
            <ray>
                <scan>
                    <horizontal>
                        <samples>10</samples>
                        <resolution>1</resolution> 
                        <min_angle>${-range_sensor_fov/2}</min_angle>
                        <max_angle>${range_sensor_fov/2}</max_angle>
                    </horizontal>
                    <vertical>
                        <samples>10</samples>
                        <resolution>1</resolution> 
                        <min_angle>${-range_sensor_fov/2}</min_angle>
                        <max_angle>${range_sensor_fov/2}</max_angle> 
                    </vertical>
                </scan>
                <range>
                    <min>0.01</min>
                    <max>${range_sensor_max_range}</max>
                    <resolution>0.02</resolution>
                </range>
            </ray>
            <plugin filename="libgazebo_ros_range.so" name="gazebo_ros_range">
                <gaussianNoise>0.005</gaussianNoise>
                <alwaysOn>true</alwaysOn>
                <updateRate>${range_sensor_update_rate}</updateRate>
                <topicName>range_sensor/ir</topicName>
                <frameName>base_ir_link</frameName>
                <radiation>INFRARED</radiation>
                <fov>${range_sensor_fov}</fov>
            </plugin>
        </sensor>  
    </gazebo>

    <!-- Illuminance Sensor: Inherits from Camera -->
    <!-- NOTE: illuminance topic == <cameraName>/illuminance -->
    <gazebo reference="light_link">
        <sensor name='light_sensor' type='camera'>
            <camera name='light_sensor'>
                <horizontal_fov>1.047</horizontal_fov>
                <image>
                    <width>320</width>
                    <height>240</height>
                    <format>R8G8B8</format>
                </image>
                <clip>
                    <near>0.01</near>
                    <far>10</far>
                </clip>
            </camera>

            <plugin name="gazebo_light_sensor_plugin" filename="libgazebo_light_sensor_plugin.so">
                <cameraName>light_sensor</cameraName>
                <alwaysOn>true</alwaysOn>
                <updateRate>50</updateRate>

                <imageTopicName>rgb/image_raw</imageTopicName>
                <depthImageTopicName>depth/image_raw</depthImageTopicName>
                <pointCloudTopicName>depth/points</pointCloudTopicName>
                <cameraInfoTopicName>rgb/camera_info</cameraInfoTopicName>
                <depthImageCameraInfoTopicName>depth/camera_info</depthImageCameraInfoTopicName>

                <frameName>light_link_optical</frameName>

                <distortion_K1>0.0</distortion_K1>
                <distortion_K2>0.0</distortion_K2>
                <distortion_K3>0.0</distortion_K3>
                <distortion_T1>0.0</distortion_T1>
                <distortion_T2>0.0</distortion_T2>
            </plugin>
        </sensor>
    </gazebo>

</robot>
